---
# tasks file for compress_backup
- name: compress backup directory
  archive:
    path: "{{ MYBACKUPDIR }}"
    dest: "{{ export_source }}"
    format: gz
    remove: no

- name: manually remove data files
  file:
    path: "{{ MYBACKUPDIR }}"
    state: absent