---
# tasks file for export_backup
- name: Copy backup tar.gz back to ansible host machine
  fetch:
    src: "{{ export_source }}"
    dest: "{{ host_dest_dir }}/"
    flat: yes

- name: Remove temp tar.gz file from master
  file:
    path: "{{ export_source }}"
    state: absent
    recurse: no
