---
# vim: ft=ansible
# Cluster openshift-health check playbook for OCP installation

- hosts: localhost
  become: false
  run_once: true
  vars:
    namespace: "app-health-check"
#    builder: "rhscl/php-56-rhel7"
#    runtime_image: "php-56-rhel7"
#    runtime_image_tag: "latest"
    sample: "httpd-example"
#    contextdir: "/opt/app-root/src"
    domain: "{{ openshift_master_default_subdomain | default('local') }}"
  collections:
    - ocp.health_check
  tasks:
    - import_role:
        name: health_check
