---
# vim: ft=ansible
# Cluster openshift-health check playbook for OCP installation

- hosts: localhost
  become: false
  run_once: true
  vars:
    namespace: "app-health-check"
    sample: "httpd-example"
    contextdir: "."
    s2i_build_local: true
    local_code_path: "{{playbook_dir}}/../src/php-apache"
    s2i_build: false
#    gitrepo: "https://github.com/akvarel/php-apache.git"
# Other variables for changing default behaviour
#    builder: "rhscl/php-56-rhel7"
#    runtime_image: "php-56-rhel7"
#    runtime_image_tag: "latest"
#    contextdir: "/opt/app-root/src"
#    port: 8080
  collections:
    - ocp.health_check
  tasks:
    - import_role:
        name: health_check
