----
# This playbook and the roles follows OCP Day-2 Operation Guide
# Tested on OCP 3.11
# Run this playbook from a control host:
# $ ansible-playbook -i inventory ocp_backup.yml
#
- name: backup master hosts
  hosts: masters
  collections:
    - ocp.backup_restore
  tasks:
    - import_role:
      name : backup_etcd
    - import_role:
      name : backup_masters
    - import_role:
      name : compress_backup

- name: ocp backup of node hosts
  hosts: nodes,!masters
  collections:
    - ocp.backup_restore
  tasks:
    - import_role:
      name : backup_nodes
    - import_role:
      name : compress_backup

- name: Set up directory for fetching tar files
  hosts: localhost
  collections:
    - ocp.backup_restore
  connection: local
  vars:
    destination_host_dir: "/tmp/ocp_backup_{{ ansible_date_time.date }}"
  tasks:
    - name: Create local temp directory for fetching files
      file:
        path: "{{ destination_host_dir }}"
        state: directory
      register: local_dir

- name: fetch tar files from all hosts
  hosts: OSEv3
  vars:
    destination_host_dir: "/tmp/ocp_backup_{{ ansible_date_time.date }}"
  tasks:
    - import_role:
      name: export_backup

### NOTES ####
# To enable sync to s3, need the following:
# yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
# yum -y install python-pip python-wheel
# pip install boto3
### END NOTES ####
### Send to S3 ####
#- name: prepare files and send backup to S3
#  hosts: localhost
#  connection: local
#  tasks:
#    - name: sync files to S3
#      s3_sync:
#        bucket: my-s3-bucket
#        key_prefix: "ocp_backup_{{ ansible_date_time.date }}"
#        file_root: "{{ hostvars['localhost'].local_dir.path }}/"
#
#    - name: remove temp files
#      file:
#        path: "{{ hostvars['localhost'].local_dir.path }}"
#        state: absent
### Send to S3 END ###
