---
- name: Ping hosts
  hosts: masters
  collections:
    - ocp.backup_restore
  vars:
    destination_host_dir: "/tmp/ocp_backup"
    glusterfs_devices_default:
      - /dev/sdb
  tasks:

    - debug:
        msg:
          - "project destination host is {{ destination_host | default(destination_host_default) | default('not found') }}"
          - "project export destination dir {{ destination_host_dir | default(destination_host_dir_default) | default('not found')}}"
          - "Date: {{ansible_date_time.epoch}} Full format: {{lookup('pipe','date +%Y%m%d-%H:%M')}}"
    - debug:
        msg:
          - "Drives: {{item}}"
      with_items: "{{ glusterfs_devices | default(glusterfs_devices_default) | list }}"

    - import_role:
        name: ping
