---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install ansible.kubernetes-modules package
      shell: ansible-galaxy install ansible.kubernetes-modules

- hosts: localhost
  remote_user: root
  tasks:
    - include_role:
        name: ansible.kubernetes-modules
    - include_role:
        name: hello-world

- name: Ping hosts
  hosts: masters
  collections:
    - ocp.backup_restore
  vars:
    destination_host_dir: "/tmp/ocp_backup"
  tasks:
    - import_role:
        name : ping

    - debug:
        msg:
        - "project destination host is {{ destination_host | default(destination_host_default) | default('not found') }}"
        - "project export destination dir {{ destination_host_dir | default(destination_host_dir_default) | default('not found')}}"
        - "Date: {{ansible_date_time.epoch}} Full format: {{lookup('pipe','date +%Y%m%d-%H:%M')}}"

    - name: Get an existing Service object
      k8s_info:
        api_version: v1
        kind: Namespace
      register: projects

    - debug:
        msg: projects

    - name: Fetch a list of namespaces
      set_fact:
        projects: "{{ lookup('k8s', api_version='v1', kind='Namespace') }}"