---
- name: Ping hosts
  hosts: masters
  collections:
    - ocp.backup_restore
  tasks:
    - import_role:
        name : ping
    - debug:
        msg: "project destination host {{ destination_host | default(destination_host_default) }}"
