---
- hosts: localhost
  tasks:
    - name: Find ansible-galaxy
      shell: which ansible-galaxy
      register: galaxy

- hosts: localhost
  tasks:
    - name: Install ansible.kubernetes-modules package
      shell: "{{galaxy.stdout}} install -r {{playbook_dir}}/../requirements.yml"
      when: remove is undefined

    - name: Install python openshift package
      shell: pip3 install openshift --user
      when: remove is undefined

    - name: Install ocp.backup_restore collection
      shell: |
        {{galaxy.stdout}} collection build {{playbook_dir}}/../ocp.backup_restore
        {{galaxy.stdout}} collection install ocp-backup_restore-1.0.0.tar.gz
        rm ocp-backup_restore-1.0.0.tar.gz
      when: remove is undefined

    - name: Remove
      shell: |
        {{galaxy.stdout}} remove ansible.kubernetes-modules
        {{galaxy.stdout}} remove ocp.backup_restore
      when: remove is defined