---
# tasks file for backup_master
- import_role:
    name: backup_node

- name: Create serials directory for the first master
  file:
      path: "{{ MYBACKUPDIR }}/serials"
      state: directory
  when: inventory_hostname == groups["masters"][0]

- name: Create serials directory for the first master
  shell: "cp -a /etc/origin/master/*.serial.txt {{ MYBACKUPDIR }}/serials"
  when: inventory_hostname == groups["masters"][0]